In [55]:
## Data Preparation -- Building Permits from FRED 
import pandas as pd
import numpy as np

In [56]:
building_permits = pd.read_csv('./data/building_permits.csv')

In [57]:
reported_columns = ['Survey_Date', 'FIPS_State', 'FIPS_County', 'Region_Code',
       'Division_Code', 'State', 'state_abbrev', 'County_Name', 'one_unit_buildings_rep',
       'one_unit_units_rep', 'one_unit_value_reps', 'two_unit_buildings_rep',
       'two_unit_units_rep', 'two_unit_value_rep', 'three_unit_building_rep',
       'three_unit_untis_rep', 'three_unit_value_rep',
       'five_unit_building_rep', 'five_unit_unit_rep', 'five_unit_value_rep']
building_permits = building_permits[reported_columns]

In [59]:
building_permits = building_permits[building_permits['Survey_Date'] == 202110]

In [60]:
zip_code_data = pd.read_csv('https://nycdsacapstone2021.blob.core.windows.net/additionaldata/ZIP_all_data.csv', index_col=0)
zip_code_data = zip_code_data.reset_index()

In [61]:
building_permits['County_Name'] =building_permits['County_Name'].str.replace("County", "").str.upper().str.strip()

In [62]:
final = pd.merge(zip_code_data, building_permits, how = 'left', left_on = ['County', 'State'], right_on = ['County_Name', 'state_abbrev'])

In [63]:
final = final.rename(columns = {'State_x' : 'State'})

In [64]:
final.to_csv('final_zip_data.csv', index = False)

In [65]:
pd.read_csv('https://nycdsacapstone2021.blob.core.windows.net/additionaldata/final_zip_data.csv')

,ZipCode,State,County,CBSA_Name,CountyFIPS,StateFIPS,Population,HouseholdsPerZipCode,WhitePopulation,BlackPopulation,...,one_unit_value_reps,two_unit_buildings_rep,two_unit_units_rep,two_unit_value_rep,three_unit_building_rep,three_unit_untis_rep,three_unit_value_rep,five_unit_building_rep,five_unit_unit_rep,five_unit_value_rep
0,20001,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,38551,16500,13671,20682,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20002,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,52370,22973,17522,33303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20003,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,26454,11724,15295,10111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20004,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,1622,1127,1321,131,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20005,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,12775,8316,8478,2157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6982,56972,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6983,56973,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6984,56998,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6985,56999,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6986,88888,DC,DISTRICT OF COLUMBIA,Washington Arlington Alexandria,1,11,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN