In [1]:
import pandas as pd
import numpy as np

In [64]:
msa_zip = pd.read_csv('ZIP_master_file.csv')

In [65]:
msa_zip.loc[msa_zip.CBSA_Name=='Jacksonville','CBSA_Name'] = \
    msa_zip[msa_zip.CBSA_Name=='Jacksonville']['CBSA_Name']+'_'+msa_zip[msa_zip.CBSA_Name=='Jacksonville']['State']

In [66]:
msa_zip.loc[msa_zip.CBSA_Name=='Gainesville','CBSA_Name'] = \
    msa_zip[msa_zip.CBSA_Name=='Gainesville']['CBSA_Name']+'_'+msa_zip[msa_zip.CBSA_Name=='Gainesville']['State']

In [67]:
data = msa_zip.groupby('CBSA_Name').agg('count')[['ZipCode']]
data.rename(columns={'ZipCode':'Zip_count'}, inplace=True)

In [118]:
# target_states = ['FL','NC','GA','VA','MD','SC','WV','DC',
#                  'GA-SC','NC-SC', 'TN-GA', 'TN-VA', 'GA-AL', 
#                  'MD-WV', 'WV-KY-OH', 'SC-NC', 'MD-DE', 'VA-NC',
#                  'DC-VA-MD-WV', 'WV-OH', 'VA-WV']

# msa_zip = pd.read_csv('MSA_to_ZIP.csv')
# msa_zip.STATE = msa_zip.STATE.str.strip()
# msa_zip.MSA = msa_zip.MSA.str.strip()
# msa_zip = msa_zip[msa_zip.STATE.isin(target_states)]

In [69]:
# msa_zip.MSA = msa_zip.MSA.str.replace('-',' ',regex=False)
# msa_zip.MSA = msa_zip.MSA.str.replace('.','',regex=False)
# msa_zip.ZIPS = msa_zip.ZIPS.astype('string')

## FRED Home Price Index Data

In [71]:
HPI = pd.read_csv('https://nycdsacapstone2021.blob.core.windows.net/fromsmh/House_Price_Index_MSA.csv?sp=r&st=2021-12-13T00:02:49Z&se=2021-12-25T08:02:49Z&spr=https&sv=2020-08-04&sr=b&sig=sciIDIM7bTIZY6FEDhaR2U8MlhAWU1sIBohmuQhAN8g%3D', 
                  index_col='Date').T.reset_index()
HPI.rename(columns={'index':'Name','Date':'index'}, inplace=True)

In [72]:
for each in ['all_transactions_house_price_index_for_','_msa']:
    HPI.Name = HPI.Name.str.replace(each,'')
#HPI.Name = HPI.Name.str.replace('all_transactions_house_price_index_for_','').str.replace('_msa','').str.replace('_',' ')
replace_states = ['FL','NC','GA','VA','MD','SC','WV','DC','TN','KY','OH','DE','AL','WVD']
for _ in range(4):
    for each in replace_states:
        HPI.Name = HPI.Name.str.replace('_'+str.lower(each)+'$','', regex=True)
HPI.Name = HPI.Name.str.replace('_',' ')

In [73]:
HPI.Name = HPI.Name.apply(lambda x: str.title(x))

In [74]:
HPI_latest = HPI[['Name','2021-07-01']].rename(columns={'2021-07-01':'HPI'}).set_index('Name')

In [75]:
HPI_latest = HPI_latest.reset_index()
print(HPI_latest[HPI_latest.Name=='Gainesville'])
print(HPI_latest[HPI_latest.Name=='Jacksonville'])

Date         Name     HPI
21    Gainesville  282.27
57    Gainesville  304.51
Date          Name     HPI
31    Jacksonville  259.52
59    Jacksonville  352.29

In [76]:
HPI_latest.loc[21,'Name'] = 'Gainsville_GA'
HPI_latest.loc[57,'Name'] = 'Gainsville_FL'
HPI_latest.loc[31,'Name'] = 'Jacksonville_NC'
HPI_latest.loc[59,'Name'] = 'Jacksonville_FL'
HPI_latest = HPI_latest.set_index('Name')

In [77]:
data = data.merge(HPI_latest, how='left', left_index=True, right_index=True)

In [78]:
pd.set_option('display.max_rows', None)
data

                                        Zip_count     HPI
CBSA_Name
Albany                                         21  187.61
Albemarle                                      10     NaN
Americus                                        8     NaN
Arcadia                                         5     NaN
Asheville                                      52  373.46
Athens Clarke County                           27  288.40
Atlanta Sandy Springs Alpharetta              320  279.86
Augusta Richmond County                        57  231.50
Bainbridge                                      7     NaN
Baltimore Columbia Towson                     202  274.54
Beckley                                        86     NaN
Bennettsville                                   6     NaN
Big Stone Gap                                   9     NaN
Blacksburg Christiansburg                      31  260.84
Bluefield                                      43     NaN
Boone                                           8     NaN
Brevard                                         8     NaN
Brunswick                                      17  272.51
Burlington                                     12  212.06
Calhoun                                         8     NaN
California Lexington Park                      28     NaN
Cambridge                                      16     NaN
Cape Coral Fort Myers                          48     NaN
Cedartown                                       4     NaN
Charleston                                    145  194.60
Charleston North Charleston                    59  420.42
Charlotte Concord Gastonia                    188  292.01
Charlottesville                                47  298.87
Chattanooga                                    12  290.77
Clarksburg                                     29     NaN
Clewiston                                       4     NaN
Columbia                                       75  230.65
Columbus                                       38  208.53
Cordele                                         3     NaN
Cornelia                                        6     NaN
Crestview Fort Walton Beach Destin             27  340.16
Cullowhee                                      12     NaN
Cumberland                                     30  187.20
Dalton                                         13  243.85
Danville                                       17     NaN
Deltona Daytona Beach Ormond Beach             54  344.25
Douglas                                        10     NaN
Dublin                                         12     NaN
Durham Chapel Hill                             47  281.50
Easton                                         15     NaN
Elizabeth City                                  7     NaN
Elkins                                         21     NaN
Eufaula                                         2     NaN
Fairmont                                       18     NaN
Fayetteville                                   33  196.37
Fitzgerald                                      1     NaN
Florence                                       21  208.33
Forest City                                    12     NaN
Gaffney                                         4     NaN
Gainesville_FL                                 43     NaN
Gainesville_GA                                 12     NaN
Georgetown                                      4     NaN
Goldsboro                                      10  199.77
Greensboro High Point                          69  212.97
Greenville                                     16  203.51
Greenville Anderson                            68  270.08
Greenwood                                      10     NaN
Hagerstown Martinsburg                         38  243.63
Harrisonburg                                   23  252.22
Henderson                                       6     NaN
Hickory Lenoir Morganton                       31  244.01
Hilton Head Island Bluffton                    25     NaN
Hinesville                                     10  207.90
Homosassa Springs                              21  303.41
Huntington Ashland                             71  208.84
Jacksonville_FL                                85  352.29
Jacksonville_NC                                13  259.52
Jefferson                                       8     NaN
Jesup                                           6     NaN
Key West                                       12     NaN
Kill Devil Hills                               14     NaN
Kingsport Bristol                              20  262.80
Kinston                                         7     NaN
LaGrange                                        5     NaN
Lake City                                       6     NaN
Lakeland Winter Haven                          55  317.70
Laurinburg                                      5     NaN
Lumberton                                      17     NaN
Lynchburg                                      38  241.70
Macon Bibb County                              34  186.82
Marion                                          5     NaN
Martinsville                                   11     NaN
Miami Fort Lauderdale Pompano Beach           290     NaN
Milledgeville                                   5     NaN
Morehead City                                  17     NaN
Morgantown                                     30  246.64
Moultrie                                        9     NaN
Mount Airy                                     11     NaN
Mount Gay Shamrock                             32     NaN
Myrtle Beach Conway North Myrtle Beach         34  293.09
Naples Marco Island                            26  409.76
New Bern                                       26     NaN
Newberry                                        9     NaN
North Port Sarasota Bradenton                  62  377.18
North Wilkesboro                               14     NaN
Ocala                                          38  286.64
Okeechobee                                      3     NaN
Orangeburg                                     18     NaN
Orlando Kissimmee Sanford                     153  333.83
Palatka                                        18     NaN
Palm Bay Melbourne Titusville                  46  348.07
Panama City                                    17  317.79
Parkersburg Vienna                             20  213.40
Pensacola Ferry Pass Brent                     38  321.73
Philadelphia Camden Wilmington PA NJ           17     NaN
Pinehurst Southern Pines                       14     NaN
Point Pleasant                                 14     NaN
Port St. Lucie                                 31     NaN
Punta Gorda                                    17  334.09
Raleigh Cary                                   79  271.68
Richmond                                      130  284.32
Roanoke                                        69  241.15
Roanoke Rapids                                 22     NaN
Rockingham                                      8     NaN
Rocky Mount                                    19  197.41
Rome                                           11  240.26
Salisbury                                      41  291.73
Sanford                                         6     NaN
Savannah                                       31  303.08
Sebastian Vero Beach                           16  336.31
Sebring Avon Park                              11  316.91
Seneca                                         13     NaN
Shelby                                         14     NaN
Spartanburg                                    38  238.56
St. Marys                                       6     NaN
Statesboro                                      7     NaN
Staunton                                       23     NaN
Summerville                                     4     NaN
Sumter                                         19     NaN
Tallahassee                                    38  258.13
Tampa St. Petersburg Clearwater               213     NaN
The Villages                                   10  321.06
Thomaston                                       3     NaN
Thomasville                                     9     NaN
Tifton                                          6     NaN
Toccoa                                          4     NaN
Union                                           6     NaN
Valdosta                                       19  209.90
Vidalia                                         8     NaN
Virginia Beach Norfolk Newport News           178  284.15
Warner Robins                                  13  191.90
Washington                                      9     NaN
Washington Arlington Alexandria               783  330.60
Wauchula                                        4     NaN
Waycross                                       11     NaN
Weirton Steubenville                           12  236.68
Wheeling                                       12  227.65
Wilmington                                     23  300.91
Wilson                                         10     NaN
Winchester                                     28  265.89
Winston Salem                                  65  220.79

## Market Hotness

In [79]:
market = pd.read_csv('https://nycdsacapstone2021.blob.core.windows.net/fromsmh/Market_Hotness_Indicators_MSA.csv?sp=r&st=2021-12-13T00:04:00Z&se=2021-12-25T08:04:00Z&spr=https&sv=2020-08-04&sr=b&sig=JmSQ5ji9hpr%2FqGKqIx5ZvFQN8q0g2ypH1glJ1%2FcsU20%3D').\
    set_index('Date').T
market = market[['2021-11-01']]
market.index = market.index.str.replace('_cbsa','')
market.drop(market.filter(regex='percent_change_', axis=0).index, inplace=True)

* Demand Score

In [80]:
demand_score = market.filter(regex='demand_score', axis=0).rename(columns={'2021-11-01':'Demand_score'})
demand_score.index = demand_score.index.str.replace('market_hotness_demand_score_in_','')
for _ in range(4):
    for each in replace_states:
        demand_score.index = demand_score.index.str.replace('_'+str.lower(each)+'$','', regex=True)
demand_score.index = demand_score.index.str.replace('_',' ').str.title()

In [82]:
demand_score = demand_score.reset_index()
print(demand_score[demand_score['index']=='Gainesville'])
print(demand_score[demand_score['index']=='Jacksonville'])

Date        index  Demand_score
18    Gainesville     36.454850
48    Gainesville     44.816054
Date         index  Demand_score
25    Jacksonville     62.876254
49    Jacksonville     32.107023

In [83]:
demand_score.loc[18,'index'] = 'Gainsville_GA'
demand_score.loc[48,'index'] = 'Gainsville_FL'
demand_score.loc[25,'index'] = 'Jacksonville_NC'
demand_score.loc[49,'index'] = 'Jacksonville_FL'
demand_score = demand_score.set_index('index')

In [87]:
data.shape

(156, 3)

In [85]:
data = data.merge(demand_score, how='left', left_index=True, right_index=True)

* Suppy Score

In [88]:
supply_score = market.filter(regex='supply_score', axis=0).rename(columns={'2021-11-01':'Supply_score'})
supply_score.index = supply_score.index.str.replace('market_hotness_supply_score_in_','')
for _ in range(4):
    for each in replace_states:
        supply_score.index = supply_score.index.str.replace('_'+str.lower(each)+'$','', regex=True)
supply_score.index = supply_score.index.str.replace('_',' ').str.title()

In [89]:
supply_score = supply_score.reset_index()
print(supply_score[supply_score['index']=='Gainesville'])
print(supply_score[supply_score['index']=='Jacksonville'])

Date        index  Supply_score
18    Gainesville     47.491639
48    Gainesville     30.100334
Date         index  Supply_score
25    Jacksonville     65.217391
49    Jacksonville     63.879599

In [90]:
supply_score.loc[18,'index'] = 'Gainsville_GA'
supply_score.loc[48,'index'] = 'Gainsville_FL'
supply_score.loc[25,'index'] = 'Jacksonville_NC'
supply_score.loc[49,'index'] = 'Jacksonville_FL'
supply_score = supply_score.set_index('index')

In [91]:
data = data.merge(supply_score, how='left', left_index=True, right_index=True)

In [94]:
data.shape

(156, 4)

* Listing Views

In [95]:
listing_views = market.filter(regex='listing_views_per_property_versus_the_united_states', axis=0).\
    rename(columns={'2021-11-01':'listviews_vs_US'})
listing_views.index = listing_views.index.str.replace('market_hotness_listing_views_per_property_versus_the_united_states_in_','')
for _ in range(4):
    for each in replace_states:
        listing_views.index = listing_views.index.str.replace('_'+str.lower(each)+'$','', regex=True)
listing_views.index = listing_views.index.str.replace('_',' ').str.title()

In [96]:
listing_views = listing_views.reset_index()
print(listing_views[listing_views['index']=='Gainesville'])
print(listing_views[listing_views['index']=='Jacksonville'])

Date        index  listviews_vs_US
18    Gainesville           0.9193
48    Gainesville           0.9743
Date         index  listviews_vs_US
25    Jacksonville           1.1632
49    Jacksonville           0.8654

In [97]:
listing_views.loc[18,'index'] = 'Gainsville_GA'
listing_views.loc[48,'index'] = 'Gainsville_FL'
listing_views.loc[25,'index'] = 'Jacksonville_NC'
listing_views.loc[49,'index'] = 'Jacksonville_FL'
listing_views = listing_views.set_index('index')

In [98]:
data = data.merge(listing_views, how='left', left_index=True, right_index=True)

In [100]:
data.shape

(156, 5)

* Median Days on Market

In [101]:
mdays_on_mkt = market.filter(regex='market_hotness_median_days_on_market_in_', axis=0).\
    rename(columns={'2021-11-01':'med_days_on_mkt'})
mdays_on_mkt.index = mdays_on_mkt.index.str.replace('market_hotness_median_days_on_market_in_','')
for _ in range(4):
    for each in replace_states:
        mdays_on_mkt.index = mdays_on_mkt.index.str.replace('_'+str.lower(each)+'$','', regex=True)
mdays_on_mkt.index = mdays_on_mkt.index.str.replace('_',' ').str.title()

In [102]:
mdays_on_mkt = mdays_on_mkt.reset_index()
print(mdays_on_mkt[mdays_on_mkt['index']=='Gainesville'])
print(mdays_on_mkt[mdays_on_mkt['index']=='Jacksonville'])

Date        index  med_days_on_mkt
18    Gainesville             46.0
48    Gainesville             50.5
Date         index  med_days_on_mkt
25    Jacksonville             42.0
49    Jacksonville             42.5

In [103]:
mdays_on_mkt.loc[18,'index'] = 'Gainsville_GA'
mdays_on_mkt.loc[48,'index'] = 'Gainsville_FL'
mdays_on_mkt.loc[25,'index'] = 'Jacksonville_NC'
mdays_on_mkt.loc[49,'index'] = 'Jacksonville_FL'
mdays_on_mkt = mdays_on_mkt.set_index('index')

In [104]:
data = data.merge(mdays_on_mkt, how='left', left_index=True, right_index=True)

In [106]:
data.shape

(156, 6)

* Nielsen Household Rank

In [107]:
nielson = market.filter(regex='nielsen_household_rank_in_', axis=0).\
    rename(columns={'2021-11-01':'nielson_rank'})
nielson.index = nielson.index.str.replace('market_hotness_nielsen_household_rank_in_','')
for _ in range(4):
    for each in replace_states:
        nielson.index = nielson.index.str.replace('_'+str.lower(each)+'$','', regex=True)
nielson.index = nielson.index.str.replace('_',' ').str.title()

In [108]:
nielson = nielson.reset_index()
print(nielson[nielson['index']=='Gainesville'])
print(nielson[nielson['index']=='Jacksonville'])

Date        index  nielson_rank
18    Gainesville         246.0
48    Gainesville         166.0
Date         index  nielson_rank
25    Jacksonville         239.0
49    Jacksonville          40.0

In [109]:
nielson.loc[18,'index'] = 'Gainsville_GA'
nielson.loc[48,'index'] = 'Gainsville_FL'
nielson.loc[25,'index'] = 'Jacksonville_NC'
nielson.loc[49,'index'] = 'Jacksonville_FL'
nielson = nielson.set_index('index')

In [110]:
data = data.merge(nielson, how='left', left_index=True, right_index=True)

In [112]:
data.shape

(156, 7)

## Unemployment

In [113]:
unemp = pd.read_excel('https://nycdsacapstone2021.blob.core.windows.net/fromsmh/BEA_unemployment.xlsx?sp=r&st=2021-12-13T01:25:18Z&se=2021-12-25T09:25:18Z&spr=https&sv=2020-08-04&sr=b&sig=dTinH9c9Ig4MPNpL51Dx4UrLu%2Fqg3mSqGyQWYcatoJE%3D',
                      header=2)
unemp = unemp[(unemp.Year==2021) & (unemp.Month==10)]

In [114]:
unemp.Area = unemp.Area.str.replace(' MSA','')

In [119]:
for each in unemp.index:
    msa = unemp.loc[each,'Area'].split(',')[0]
    state = unemp.loc[each,'Area'].split(',')[1]
    unemp.loc[each,'MSA'] = msa
    unemp.loc[each,'STATE'] = state
unemp.STATE = unemp.STATE.str.strip()
unemp = unemp[unemp.STATE.isin(target_states)]

In [120]:
unemp['MSA'] = unemp.MSA.str.replace('. ',' ', regex=False).str.replace('-',' ', regex=False)

<ipython-input-120-af6c143c1cd0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemp['MSA'] = unemp.MSA.str.replace('. ',' ', regex=False).str.replace('-',' ', regex=False)

In [127]:
unemp[['MSA','STATE']]

                                           MSA        STATE
150944                               Salisbury        MD-DE
150945         Washington Arlington Alexandria  DC-VA-MD-WV
150946                   Cape Coral Fort Myers           FL
150947      Crestview Fort Walton Beach Destin           FL
150948      Deltona Daytona Beach Ormond Beach           FL
150949                           Gainsville_FL           FL
150950                       Homosassa Springs           FL
150951                         Jacksonville_FL           FL
150952                   Lakeland Winter Haven           FL
150953   Miami Fort Lauderdale West Palm Beach           FL
150954           Naples Immokalee Marco Island           FL
150955           North Port Sarasota Bradenton           FL
150956                                   Ocala           FL
150957               Orlando Kissimmee Sanford           FL
150958           Palm Bay Melbourne Titusville           FL
150959                             Panama City           FL
150960              Pensacola Ferry Pass Brent           FL
150961                           Port St Lucie           FL
150962                             Punta Gorda           FL
150963                    Sebastian Vero Beach           FL
150964                                 Sebring           FL
150965                             Tallahassee           FL
150966          Tampa St Petersburg Clearwater           FL
150967                            The Villages           FL
150968                                  Albany           GA
150969                    Athens Clarke County           GA
150970           Atlanta Sandy Springs Roswell           GA
150971                 Augusta Richmond County        GA-SC
150972                               Brunswick           GA
150973                                Columbus        GA-AL
150974                                  Dalton           GA
150975                           Gainsville_GA           GA
150976                              Hinesville           GA
150977                       Macon Bibb County           GA
150978                                    Rome           GA
150979                                Savannah           GA
150980                                Valdosta           GA
150981                           Warner Robins           GA
151041               Baltimore Columbia Towson           MD
151042               California Lexington Park           MD
151043                              Cumberland        MD-WV
151044                  Hagerstown Martinsburg        MD-WV
151114                               Asheville           NC
151115                              Burlington           NC
151116              Charlotte Concord Gastonia        NC-SC
151117                      Durham Chapel Hill           NC
151118                            Fayetteville           NC
151119                               Goldsboro           NC
151120                   Greensboro High Point           NC
151121                              Greenville           NC
151122                Hickory Lenoir Morganton           NC
151123                         Jacksonville_NC           NC
151124                                New Bern           NC
151125                                 Raleigh           NC
151126                             Rocky Mount           NC
151127                              Wilmington           NC
151128                           Winston Salem           NC
151142                    Weirton Steubenville        WV-OH
151175             Charleston North Charleston           SC
151176                                Columbia           SC
151177                                Florence           SC
151178             Greenville Anderson Mauldin           SC
151179    Hilton Head Island Bluffton Beaufort           SC
151180  Myrtle Beach Conway North Myrtle Beach        SC-NC
151181                             Spartanburg           SC
151182                                  Sumter           SC
151185                             Chattanooga        TN-GA
151190               Kingsport Bristol Bristol        TN-VA
151226       Blacksburg Christiansburg Radford           VA
151227                         Charlottesville           VA
151228                            Harrisonburg           VA
151229                               Lynchburg           VA
151230                                Richmond           VA
151231                                 Roanoke           VA
151232                     Staunton Waynesboro           VA
151233     Virginia Beach Norfolk Newport News        VA-NC
151234                              Winchester        VA-WV
151246                                 Beckley           WV
151247                              Charleston           WV
151248                      Huntington Ashland     WV-KY-OH
151249                              Morgantown           WV
151250                      Parkersburg Vienna           WV
151251                                Wheeling        WV-OH

In [125]:
print(unemp.loc[unemp['MSA']=='Gainesville',['MSA','STATE']])
print(unemp.loc[unemp['MSA']=='Jacksonville',['MSA','STATE']])

                MSA STATE
150949  Gainesville    FL
150975  Gainesville    GA
                 MSA STATE
150951  Jacksonville    FL
151123  Jacksonville    NC

In [126]:
unemp.loc[150975,'MSA'] = 'Gainsville_GA'
unemp.loc[150949,'MSA'] = 'Gainsville_FL'
unemp.loc[151123,'MSA'] = 'Jacksonville_NC'
unemp.loc[150951,'MSA'] = 'Jacksonville_FL'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [128]:
data = data.merge(unemp.set_index('MSA')['Unemployment Rate'], how='left', left_index=True, right_index=True)
data.rename(columns={'Unemployment Rate':'UE_rate'}, inplace=True)

In [130]:
data.shape

(156, 8)

In [131]:
data.to_csv('MSA_data.csv')